import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from "next/router";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  const queryParams = new URLSearchParams(router.asPath.split("?")[1]);

  const handleParams = () => {
    const currentStatus = 'abc';
    const urlRecordsPerpage = 'xyz'
    if (true) {
      router.push(`/?status=${currentStatus}&recordsPerpage=${urlRecordsPerpage}`, undefined, { shallow: true })
      // router.push(`/orders?status=${currentStatus}&recordsPerpage=${urlRecordsPerpage}&startDate=${urlStartDate}&endDate=${urlEndDate}&search=${searchBar}`, undefined, { shallow: true })
    } else {
      router.push(`/orders?vcStatus==${currentStatus}&recordsPerpage=${urlRecordsPerpage}`, undefined, { shallow: true })
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image
          src="/vercel.svg"
          alt="Vercel Logo"

          onClick={handleParams}
          className={styles.vercelLogo}
          width={100}
          height={24}
          priority
        />
      </main>
    </>
  )
}
